import camera from "./plugin/camera";
import mapLocation from "./plugin/location";
import file from "./plugin/file";
import "./plugin/screenOrientation.ts";
import "./plugin/keyboard.ts";
import "./lifecycles.js";
window.plugin = {};
window.plugin.camera = camera;
window.plugin.mapLocation = mapLocation;
window.plugin.file = file;
